<a href="https://colab.research.google.com/github/BasamYashwanth/Data-Science/blob/main/DS_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("//content/students_data.csv",parse_dates=['name'])
type(df.name[0])
df

/tmp/ipykernel_963/171422855.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("//content/students_data.csv",parse_dates=['name'])

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [ ]:
df.duplicated().any()

np.True_

In [ ]:
df[df.duplicated(keep=False)]

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [ ]:
df.rename(columns={
    'name': 'Student_Name',
    'age': 'Student_Age',
    'student_id': 'ID',
    'math_score': 'Math'
}, inplace=True)

In [ ]:
print(df.columns)

Index(['ID', 'Student_Name', 'Student_Age', 'gender', 'grade', 'Math',
       'english_score', 'science_score', 'enrolled_date', 'remarks'],
      dtype='object')